import { useQuery } from "@tanstack/react-query";
import { Navigation, MobileNav } from "@/components/Navigation";
import { 
  Activity, 
  Wallet, 
  BarChart3, 
  RefreshCw, 
  AlertCircle,
  ShieldCheck,
  Zap,
  Terminal,
  Copy,
  Check,
  FileJson
} from "lucide-react";
import { cn } from "@/lib/utils";
import { formatDistanceToNow } from "date-fns";
import { useState } from "react";
import { useToast } from "@/hooks/use-toast";

export default function MT5Bridge() {
  const { toast } = useToast();
  const [copied, setCopied] = useState(false);
  const { data: mt5, isLoading, error, refetch } = useQuery({
    queryKey: ["/api/mt5/status"],
    refetchInterval: 2000, 
  });

  const eaCode = `// TRADIFY MT5 Local Bridge EA
#property copyright "TRADIFY"
#property version   "1.00"
#property strict

input int UpdateInterval = 2; // seconds

int OnInit() {
   EventSetTimer(UpdateInterval);
   return(INIT_SUCCEEDED);
}

void OnDeinit(const int reason) {
   EventKillTimer();
}

void OnTimer() {
   string json = "{";
   json += "\\"account\\":{";
   json += "\\"balance\\":" + DoubleToString(AccountInfoDouble(ACCOUNT_BALANCE), 2) + ",";
   json += "\\"equity\\":" + DoubleToString(AccountInfoDouble(ACCOUNT_EQUITY), 2) + ",";
   json += "\\"profit\\":" + DoubleToString(AccountInfoDouble(ACCOUNT_PROFIT), 2) + ",";
   json += "\\"margin_level\\":" + DoubleToString(AccountInfoDouble(ACCOUNT_MARGIN_LEVEL), 2);
   json += "},\\"positions\\":[";
   
   int pos_count = 0;
   for(int i=0; i<PositionsTotal(); i++) {
      ulong ticket = PositionGetTicket(i);
      if(PositionSelectByTicket(ticket)) {
         if(pos_count > 0) json += ",";
         json += "{";
         json += "\\"symbol\\":\\"" + PositionGetString(POSITION_SYMBOL) + "\\",";
         json += "\\"type\\":\\"" + (PositionGetInteger(POSITION_TYPE) == POSITION_TYPE_BUY ? "Buy" : "Sell") + "\\",";
         json += "\\"volume\\":" + DoubleToString(PositionGetDouble(POSITION_VOLUME), 2) + ",";
         json += "\\"price_open\\":" + DoubleToString(PositionGetDouble(POSITION_PRICE_OPEN), 5) + ",";
         json += "\\"profit\\":" + DoubleToString(PositionGetDouble(POSITION_PROFIT), 2);
         json += "}";
         pos_count++;
      }
   }
   json += "],\\"last_update\\":" + IntegerToString(TimeCurrent()) + "}";

   int handle = FileOpen("TRADIFY_bridge_data.json", FILE_WRITE | FILE_COMMON | FILE_ANSI);
   if(handle != INVALID_HANDLE) {
      FileWriteString(handle, json);
      FileClose(handle);
   } else {
      Print("TRADIFY ERROR: Cannot write file. Error: ", GetLastError());
   }
}`;

  const copyToClipboard = () => {
    navigator.clipboard.writeText(eaCode);
    setCopied(true);
    toast({
      title: "Copied to clipboard",
      description: "Paste this into your MetaEditor and compile as an EA.",
    });
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="min-h-screen bg-slate-950 text-slate-50 pb-20 md:pb-0">
      <Navigation />
      <MobileNav />
      
      <main className="md:ml-64 p-6 lg:p-10 max-w-6xl mx-auto">
        <header className="mb-8 flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <div className="flex items-center gap-2 mb-1">
              <div className={cn(
                "w-2 h-2 rounded-full",
                mt5 ? "bg-emerald-500 animate-pulse" : "bg-slate-700"
              )} />
              <h1 className="text-3xl font-bold text-white tracking-tight">MT5 Bridge</h1>
            </div>
            <p className="text-slate-400">Local File-Based Synchronization (Stable)</p>
          </div>
          <button 
            onClick={() => refetch()}
            className="flex items-center gap-2 bg-slate-900 border border-slate-800 px-4 py-2 rounded-lg text-sm font-medium hover:bg-slate-800 transition-colors"
          >
            <RefreshCw size={16} className={cn(isLoading && "animate-spin")} />
            Refresh
          </button>
        </header>

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
          <div className="lg:col-span-7 space-y-8">
            <div className="bg-amber-500/10 border border-amber-500/20 rounded-xl p-6 mb-6">
              <div className="flex items-center gap-2 text-amber-500 mb-2">
                <ShieldCheck size={18} />
                <h3 className="font-bold uppercase tracking-widest text-xs">Switching to Local Bridge</h3>
              </div>
              <p className="text-sm text-slate-400 leading-relaxed">
                MT5 cloud connections are often unstable. We are switching to a <strong>Local File Bridge</strong>. 
                This app will now look for the <code>TRADIFY_bridge_data.json</code> file generated by MT5 on your device.
              </p>
            </div>

            {error ? (
              <div className="bg-rose-500/10 border border-rose-500/20 rounded-xl p-8 text-center">
                <AlertCircle size={48} className="mx-auto text-rose-500 mb-4" />
                <h3 className="text-xl font-bold text-white mb-2">Bridge Not Detected</h3>
                <p className="text-slate-400">Please ensure the EA is running and writing the bridge file.</p>
              </div>
            ) : !mt5 ? (
              <div className="bg-slate-900 border border-slate-800 rounded-xl p-8 text-center">
                <FileJson size={48} className="mx-auto text-slate-700 mb-4" />
                <h3 className="text-xl font-bold text-white mb-2">Waiting for File</h3>
                <p className="text-slate-400 max-w-md mx-auto mb-6">
                  Follow the instructions on the right to start the local bridge.
                </p>
              </div>
            ) : (
              <div className="space-y-6">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 shadow-sm">
                    <div className="flex items-center justify-between mb-4">
                      <span className="text-xs font-bold text-slate-500 uppercase tracking-widest">Balance</span>
                      <Wallet className="text-emerald-500" size={18} />
                    </div>
                    <div className="text-2xl font-mono font-bold text-white">
                      ${mt5.accountInfo?.balance?.toLocaleString()}
                    </div>
                  </div>
                  <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 shadow-sm">
                    <div className="flex items-center justify-between mb-4">
                      <span className="text-xs font-bold text-slate-500 uppercase tracking-widest">Profit/Loss</span>
                      <Activity className={cn(mt5.accountInfo?.profit >= 0 ? "text-emerald-500" : "text-rose-500")} size={18} />
                    </div>
                    <div className={cn(
                      "text-2xl font-mono font-bold",
                      mt5.accountInfo?.profit >= 0 ? "text-emerald-500" : "text-rose-500"
                    )}>
                      ${mt5.accountInfo?.profit?.toLocaleString()}
                    </div>
                  </div>
                </div>

                <div className="bg-slate-900 border border-slate-800 rounded-xl overflow-hidden shadow-sm">
                  <div className="px-6 py-4 border-b border-slate-800 flex items-center justify-between">
                    <h3 className="font-bold flex items-center gap-2 text-sm uppercase tracking-widest">
                      <BarChart3 size={16} className="text-slate-500" />
                      Open Positions ({mt5.positions?.length || 0})
                    </h3>
                  </div>
                  <div className="overflow-x-auto">
                    <table className="w-full text-left">
                      <thead>
                        <tr className="bg-slate-950/50 text-[10px] font-bold text-slate-500 uppercase tracking-widest">
                          <th className="px-6 py-3">Symbol</th>
                          <th className="px-6 py-3">Type</th>
                          <th className="px-6 py-3 text-right">Profit</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-slate-800">
                        {mt5.positions?.map((pos: any, idx: number) => (
                          <tr key={idx} className="hover:bg-slate-800/30 transition-colors">
                            <td className="px-6 py-4 font-mono text-sm text-white">{pos.symbol}</td>
                            <td className="px-6 py-4">
                              <span className={cn(
                                "text-[10px] font-bold px-2 py-0.5 rounded uppercase tracking-wider",
                                pos.type === "Buy" ? "bg-emerald-500/10 text-emerald-500" : "bg-rose-500/10 text-rose-500"
                              )}>
                                {pos.type}
                              </span>
                            </td>
                            <td className={cn(
                              "px-6 py-4 font-mono text-sm text-right font-bold",
                              pos.profit >= 0 ? "text-emerald-500" : "text-rose-500"
                            )}>
                              ${pos.profit?.toFixed(2)}
                            </td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            )}
          </div>

          <div className="lg:col-span-5 space-y-6">
            <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 shadow-lg">
              <h3 className="text-sm font-bold text-white uppercase tracking-widest mb-4 flex items-center gap-2">
                <Terminal size={16} className="text-emerald-500" />
                Local Setup Steps
              </h3>
              <ol className="space-y-4 text-sm text-slate-400">
                <li className="flex gap-3">
                  <span className="flex-shrink-0 w-5 h-5 rounded-full bg-slate-800 flex items-center justify-center text-[10px] font-bold text-emerald-500">1</span>
                  <span>Copy and Compile the EA below.</span>
                </li>
                <li className="flex gap-3">
                  <span className="flex-shrink-0 w-5 h-5 rounded-full bg-slate-800 flex items-center justify-center text-[10px] font-bold text-emerald-500">2</span>
                  <span>Attach it to any chart in MT5.</span>
                </li>
                <li className="flex gap-3">
                  <span className="flex-shrink-0 w-5 h-5 rounded-full bg-slate-800 flex items-center justify-center text-[10px] font-bold text-emerald-500">3</span>
                  <span>The bridge will write to <strong>File Common Folder</strong>.</span>
                </li>
              </ol>

              <div className="mt-6 relative group">
                <div className="absolute top-2 right-2 z-10">
                  <button 
                    onClick={copyToClipboard}
                    className="p-2 bg-slate-800 hover:bg-slate-700 rounded-md transition-colors text-slate-300"
                  >
                    {copied ? <Check size={14} className="text-emerald-500" /> : <Copy size={14} />}
                  </button>
                </div>
                <div className="bg-slate-950 rounded-lg p-4 font-mono text-[10px] text-slate-500 h-64 overflow-y-auto border border-slate-800 group-hover:border-emerald-500/30 transition-colors">
                  <pre>{eaCode}</pre>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
