// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/reports/CompetitiveAnalysis.tsx": () => import("../components/mockups/reports/CompetitiveAnalysis.tsx"),
  "./components/mockups/ads/ContrastCarousel.tsx": () => import("../components/mockups/ads/ContrastCarousel.tsx"),
  "./components/mockups/ads/ContrastPost.tsx": () => import("../components/mockups/ads/ContrastPost.tsx"),
  "./components/mockups/ads/ContrastReel.tsx": () => import("../components/mockups/ads/ContrastReel.tsx"),
  "./components/mockups/ads/IdentityCarousel.tsx": () => import("../components/mockups/ads/IdentityCarousel.tsx"),
  "./components/mockups/ads/IdentityPost.tsx": () => import("../components/mockups/ads/IdentityPost.tsx"),
  "./components/mockups/ads/IdentityReel.tsx": () => import("../components/mockups/ads/IdentityReel.tsx"),
  "./components/mockups/ads/PainCarousel.tsx": () => import("../components/mockups/ads/PainCarousel.tsx"),
  "./components/mockups/ads/PainPost.tsx": () => import("../components/mockups/ads/PainPost.tsx"),
  "./components/mockups/ads/PainReel.tsx": () => import("../components/mockups/ads/PainReel.tsx")
};
